library/urls.py
from django.urls import path
from library.views import (
    index, register, login, logout, dashboard, books_listing, book_details, top_ten_books, reserve_book
)


app_name = 'library'
urlpatterns = [
    path('', index, name='index'),
    path('books/', books_listing, name='books_listing'),
    path('books/<int:book_id>', book_details, name='book_details'),
    path('top-ten-books/', top_ten_books, name='top_ten_books'),
    path('reserve/<int:book_id>/', reserve_book, name='reserve_book'),
    path('register/', register, name='register'),
    path('login/', login, name='login'),
    path('logout/', logout, name='logout'),
    path('dashboard/', dashboard, name='dashboard'),
]

library_management_system/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from drf_spectacular.views import SpectacularAPIView, SpectacularSwaggerView, SpectacularRedocView
from library_management_system import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('library.urls', namespace='library')),
    path('rest-api/', include('rest_api.urls', namespace='rest_api')),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    path('statistics-api/', include('statistics_api.urls', namespace='statistics_api')),
    path('schema/', SpectacularAPIView.as_view(), name='schema'),
    path('schema/swagger-ui/', SpectacularSwaggerView.as_view(url_name='schema'), name='swagger-ui'),
    path('schema/redoc/', SpectacularRedocView.as_view(url_name='schema'), name='redoc'),
]


if settings.DEBUG:
    urlpatterns += [path("__debug__/", include("debug_toolbar.urls"))]
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

library/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from users.models import User
from django.utils.translation import gettext_lazy as _
from library.utils import default_return_date, default_expiration_date


class Customer(models.Model):
    user = models.OneToOneField(
        User,
        on_delete=models.CASCADE,
        related_name='customer_profile',
        verbose_name=_('User')
    )
    email = models.EmailField(_('Email'), unique=True)
    full_name = models.CharField(_('Full Name'), max_length=255)
    personal_number = models.CharField(_('Personal Number'), max_length=11, unique=True)
    birth_date = models.DateField(_('Birth Date'))

    def __str__(self):
        return self.full_name

    class Meta:
        verbose_name = _('Customer')
        verbose_name_plural = _('Customers')


class Author(models.Model):
    full_name = models.CharField(_('Full Name'), max_length=255)

    def __str__(self):
        return self.full_name

    class Meta:
        verbose_name = _('Author')
        verbose_name_plural = _('Authors')
        ordering = ['full_name']


class Genre(models.Model):
    genre = models.CharField(_('Genre'), max_length=100)

    def __str__(self):
        return self.genre

    class Meta:
        verbose_name = _('Genre')
        verbose_name_plural = _('Genres')
        ordering = ['genre']


class Book(models.Model):
    authors = models.ManyToManyField(Author, related_name='books', verbose_name=_('Authors'))
    genres = models.ManyToManyField(Genre, related_name='books', verbose_name=_('Genres'))
    title = models.CharField(_('Title'), max_length=255)
    image = models.URLField(_('Image'), max_length=255)
    date_published = models.DateField(_('Date Published'))
    stock = models.PositiveIntegerField(_('Stock'))

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = _('Book')
        verbose_name_plural = _('Books')
        ordering = ['-id']


class Checkout(models.Model):
    book = models.ForeignKey(Book, on_delete=models.CASCADE, verbose_name=_('Book'))
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE, verbose_name=_('Customer'))
    checkout_date = models.DateTimeField(_('Checkout Date'), auto_now_add=True)
    return_date = models.DateTimeField(_('Return Date'), null=True, blank=True)
    expected_return_date = models.DateTimeField(_('Expected Return Date'), default=default_return_date)
    is_returned = models.BooleanField(_('Is Returned'), default=False)

    def __str__(self):
        return f'{self.book.title} checked out by {self.customer.full_name}'

    class Meta:
        verbose_name = _('Checkout')
        verbose_name_plural = _('Checkouts')
        ordering = ['-id']


class Reservation(models.Model):
    book = models.ForeignKey(Book, on_delete=models.CASCADE, verbose_name=_('Book'))
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE, verbose_name=_('Customer'))
    reservation_date = models.DateTimeField(_('Reservation Date'), auto_now_add=True)
    expiration_date = models.DateTimeField(_('Expiration Date'), default=default_expiration_date)

    def __str__(self):
        return f'{self.book.title} reserved by {self.customer.full_name}'

    class Meta:
        verbose_name = _('Reservation')
        verbose_name_plural = _('Reservations')
        ordering = ['-id']

library/helper_classes/forms.py
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.forms.fields import CharField, DateField, EmailField
from django import forms
from users.models import User


class CreateUserForm(UserCreationForm):
    full_name = CharField(
        max_length=255,
        required=True,
        widget=forms.TextInput(attrs={'type': 'text', 'class': 'form-control', 'placeholder': 'Jon Doe'})
    )
    personal_number = CharField(
        max_length=11,
        required=True,
        widget=forms.TextInput(attrs={'type': 'number', 'class': 'form-control', 'placeholder': '01028279966'})
    )
    birth_date = DateField(
        widget=forms.DateInput(attrs={'type': 'date', 'class': 'form-control'})
    )
    email = EmailField(
        widget=forms.EmailInput(attrs={'class': 'form-control', 'placeholder': 'user@gmail.com'}),
        max_length=64,
    )
    password1 = CharField(
        widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Password'})
    )
    password2 = CharField(
        widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Password Again'})
    )

    class Meta:
        model = User
        fields = ('full_name', 'personal_number', 'birth_date', 'email', 'password1', 'password2')


class LoginForm(AuthenticationForm):
    username = forms.EmailField(
        widget=forms.EmailInput(attrs={'class': 'form-control', 'placeholder': 'user@gmail.com'}),
        label='Email'
    )
    password = forms.CharField(
        widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Password'}),
        label='Password'
    )

    def __init__(self, *args, **kwargs):
        super(LoginForm, self).__init__(*args, **kwargs)
        self.fields['username'].label = "Email"
        self.fields['username'].widget.attrs['placeholder'] = 'user@gmail.com'
        self.fields['password'].widget.attrs['placeholder'] = 'Password'

library/views.py
from django.core.paginator import Paginator
from django.db.models import Q, Count
from django.shortcuts import render, redirect, get_object_or_404
from library.helper_classes.forms import CreateUserForm, LoginForm
from library.models import Customer, Book, Reservation, Checkout
from django.db import IntegrityError
from django.contrib.auth import authenticate, login as auth_login, logout as auth_logout
from django.contrib.auth.decorators import login_required
from django.contrib import messages


def index(request):
    return render(request, 'library/index.html')


def books_listing(request):
    if request.GET.get('filter'):
        filter_property: str = request.GET.get('filter')
        books = Book.objects.filter(
            Q(title__icontains=filter_property) |
            Q(authors__full_name__icontains=filter_property)
        ).distinct()
    else:
        books = Book.objects.all()
    paginator = Paginator(books, 8)
    page_num = int(request.GET.get('page', 1))
    page = paginator.get_page(page_num)

    return render(request, 'library/books.html', {'page': page})


def top_ten_books(request):
    books = (
        Book.objects
        .annotate(checkout_count=Count('checkout'))
        .order_by('-checkout_count')[:10]
    )

    return render(request, 'library/top_ten_books.html', {'books': books})


def book_details(request, book_id):
    book = get_object_or_404(Book, pk=book_id)
    authors = book.authors.all()
    genres = book.genres.all()

    context = {'book': book, 'authors': authors, 'genres': genres}
    return render(request, 'library/book_details.html', context=context)


@login_required
def reserve_book(request, book_id):
    book = get_object_or_404(Book, id=book_id)
    customer = get_object_or_404(Customer, user=request.user)

    if Reservation.objects.filter(customer=customer).exists():
        messages.error(
            request,
            message="You already have a reserved book. You can't reserve more than one book.",
            extra_tags="danger"
        )
        return redirect('library:book_details', book_id=book_id)

    if book.stock < 1:
        messages.error(request, "This book is currently out of stock.", "danger")
        return redirect('library:book_details', book_id=book_id)

    Reservation.objects.create(
        book=book,
        customer=customer
    )
    book.stock -= 1
    book.save(update_fields=('stock',))

    messages.success(request, f"You have successfully reserved '{book.title}'.", "success")
    return redirect('library:book_details', book_id=book_id)


def register(request):
    form = CreateUserForm()

    if request.method == 'POST':
        form = CreateUserForm(request.POST)

        if form.is_valid():
            try:
                user = form.save(commit=False)
                email = form.cleaned_data.get('email')
                full_name = form.cleaned_data.get('full_name')
                personal_number = form.cleaned_data.get('personal_number')
                birth_date = form.cleaned_data.get('birth_date')

                user.first_name = full_name.split()[0]
                user.last_name = ' '.join(full_name.split(' ')[1:])
                user.save()

                customer = Customer.objects.create(
                    user=user,
                    email=email,
                    full_name=full_name,
                    personal_number=personal_number,
                    birth_date=birth_date
                )
                customer.save()
                return redirect('library:login')
            except IntegrityError:
                form.add_error('personal_number', 'A customer with this personal number already exists.')
                user.delete()

    context = {'form': form}
    return render(request, 'library/register.html', context=context)


def login(request):
    form = LoginForm()

    if request.method == 'POST':
        form = LoginForm(request, data=request.POST)

        if form.is_valid():
            email = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(request, email=email, password=password)

            if user is not None:
                auth_login(request, user)
                return redirect('library:dashboard')
            else:
                form.add_error('username', 'Email or password is incorrect.')

    context = {'form': form}

    return render(request, 'library/login.html', context=context)


def logout(request):
    auth_logout(request)
    return redirect('library:index')


@login_required(login_url='library:login')
def dashboard(request):
    user = request.user
    customer = Customer.objects.get(user=user)
    reservations = Reservation.objects.filter(customer=customer)
    checkouts = Checkout.objects.filter(customer=customer)

    context = {
        'user': user,
        'customer': customer,
        'reservations': reservations,
        'checkouts': checkouts,
    }

    return render(request, 'library/dashboard.html', context)

library/templates/library/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Library Management System{% endblock %}</title>
    <link rel="shortcut icon" type="image/png" href="{% static 'library/imgs/book.png' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css" integrity="sha512-SnH5WK+bZxgPHs44uWIX+LLJAJ9/2PkPKZ5QiAj6Ta86w+fsb2TkcmfRyVX3pBnMFcV7oQPJkl9QevSCWr3W6A==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="{% static 'library/css/base.css' %}">
    {% block extra_css %}{% endblock %}
</head>
<body>
<header>
    {% if messages %}
        <div class="p-4 messages-cont">
            {% for message in messages %}
                <div class="alert alert-{{ message.extra_tags }} alert-dismissible fade show" role="alert">
                    {{ message }}
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
            {% endfor %}
        </div>
    {% endif %}
    <nav class="navbar navbar-expand-lg nav-cont border-bottom py-0">
        <div class="container-fluid py-0 py-3 py-lg-0">
            <button class="navbar-toggler border-0 nav-btn ps-0 ps-sm-2" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvas">
                <span><svg width="16" height="15" xmlns="http://www.w3.org/2000/svg"><path d="M16 12v3H0v-3h16Zm0-6v3H0V6h16Zm0-6v3H0V0h16Z" fill="#69707D" fill-rule="evenodd"/></svg></span>
            </button>
            <a href="{% url 'library:index' %}" class="navbar-brand mx-0 ms-sm-2 me-sm-3"><img src="{% static 'library/imgs/book.png' %}"></a>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav ms-4 mt-1 p-0">
                    <li class="nav-item ms-3">
                        <a href="{% url 'library:books_listing' %}" class="nav-link py-4 nav-a">Books</a>
                    </li>
                    <li class="nav-item ms-3">
                        <a href="{% url 'library:top_ten_books' %}" class="nav-link py-4 nav-a">Top 10</a>
                    </li>
                </ul>
            </div>
            <div class="rt-nav-items ms-auto d-flex align-items-between pe-3">
                {% if user.is_authenticated %}
                    <a href="{% url 'library:logout' %}" class="nav-link me-3 mt-1">Logout</a>
                    <a href="{% url 'library:dashboard' %}"><img alt="profile-icon" class="avatar-img-cont" src="{% static 'library/imgs/user.png' %}"></a>
                {% else %}
                    <a href="{% url 'library:login' %}" class="nav-link ms-2">Login</a>
                {% endif %}
            </div>
            <!-- offcanvas -->
            <div class="offcanvas offcanvas-start" tabindex="-1" id="offcanvas">
                <div class="offcanvas-header">
                    <button type="button" class="btn-close mt-2" data-bs-dismiss="offcanvas"></button>
                </div>
                <div class="offcanvas-body">
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <a href="{% url 'library:books_listing' %}" class="nav-link py-2 py-md-3 nav-a">Books</a>
                        </li>
                        <li class="nav-item">
                            <a href="{% url 'library:top_ten_books' %}" class="nav-link py-2 py-md-3 nav-a">Top 10</a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </nav>
</header>
<main class="container">
    {% block content %}
    {% endblock %}
</main>
<footer>
    <p>&copy; 2024 Library Management System</p>
</footer>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
{% block extra_js %}{% endblock %}
</body>
</html>

library/templates/library/book_details.html
{% extends 'library/base.html' %}
{% load static %}
{% block extra_css %}
    <link rel="stylesheet" href="{% static 'library/css/book_details.css' %}">
{% endblock %}
{% block title %}Book Details{% endblock %}
{% block content %}
<h1>Book Details</h1>
<div class="details-cont">
    <img class="details-cont-img" src="{{ book.image }}" alt="{{ book.title }} image.">
    <div class="details-cont-body">
        <h2 class="book-name">{{ book.name }}</h2>
        <p><span class="param-title">Authors:</span>
            {% for author in authors %}
                {{ author.full_name }}{% if not forloop.last %},{% endif %}
            {% endfor %}
        </p>
        <p><span class="param-title">Categories:</span>
            {% for genre in genres %}
                {{ genre.genre }}{% if not forloop.last %},{% endif %}
            {% endfor %}
        </p>
        <p><span class="param-title">Date Published:</span> {{ book.date_published }}</p>
        <p><span class="param-title">Stock:</span> {{ book.stock }}</p>
        <a class="back-btn" href="{% url 'library:reserve_book' book.id %}">Reserve</a>
    </div>
</div>
{% endblock %}

library/templates/library/books.html
{% extends 'library/base.html' %}
{% load static %}
{% block extra_css %}
    <link rel="stylesheet" href="{% static 'library/css/books.css' %}">
{% endblock %}
{% block title %}Book Listing{% endblock %}
{% block content %}
    <h1>Books</h1>
    <form method="GET" class="search-form">
        <div class="container d-flex justify-content-center">
            <div class="card mt-5 p-4">
                <div class="input-group mb-3">
                    <input type="text" class="form-control" name="filter">
                    <div class="input-group-append"><button type="submit" class="btn btn-primary"><i class="fas fa-search"></i></button></div>
                </div>
            </div>
        </div>
    </form>
    <div class="books-cont">
        <div class="books-list">
            {% for book in page.object_list %}
                <div class="books-list-item">
                    <a href="{% url "library:book_details" book.pk %}">
                        <img src="{{ book.image }}" alt="{{ book.title }} image">
                    </a>
                    <div class="books-list-item-body">
                        <p>{{ book.title }}</p>
                        <p><span class="param-title">authors:</span>
                            {% for author in book.authors.all %}
                                {{ author.full_name }}{% if not forloop.last %},{% endif %}
                            {% endfor %}
                        </p>
                    </div>
                </div>
            {% endfor %}
        </div>
        <div class="pagination-cont">
            {% if page.has_previous %}
                <a class="pagination-btn" href="{% url "library:books_listing" %}?page={{ page.previous_page_number }}{% if request.GET.filter %}&filter={{ request.GET.filter }}{% endif %}">Prev</a>
            {% else %}
                <a class="pagination-btn" disabled>Prev</a>
            {% endif %}

            <span class="current">Page {{ page.number }} of {{ page.paginator.num_pages }}</span>

            {% if page.has_next %}
                <a class="pagination-btn" href="{% url "library:books_listing" %}?page={{ page.next_page_number }}{% if request.GET.filter %}&filter={{ request.GET.filter }}{% endif %}">Next</a>
            {% else %}
                <a class="pagination-btn" disabled>Next</a>
            {% endif %}
        </div>
    </div>
{% endblock %}

library/templates/library/dashboard.html
{% extends 'library/base.html' %}

{% block title %}Dashboard{% endblock %}

{% block content %}
    <h1>Dashboard</h1>

    <div class="card user-info p-3 mb-4 rounded-3">
        <div class="card-body">
            <h2 class="border-bottom mb-4">User Information</h2>
            <p><strong>Email:</strong> {{ user.email }}</p>
            <p><strong>Full Name:</strong> {{ customer.full_name }}</p>
            <p><strong>Personal Number:</strong> {{ customer.personal_number }}</p>
            <p><strong>Birth Date:</strong> {{ customer.birth_date }}</p>
        </div>
    </div>

    <div class="card reservations p-3 mb-4 rounded-3">
        <div class="card-body">
            <h2 class="border-bottom mb-4">Reservations</h2>
            {% if reservations %}
                <ul>
                    {% for reservation in reservations %}
                        <li>
                            <strong>Book:</strong> {{ reservation.book.title }}<br>
                            <strong>Reservation Date:</strong> {{ reservation.reservation_date }}<br>
                            <strong>Expiration Date:</strong> {{ reservation.expiration_date }}
                        </li>
                    {% endfor %}
                </ul>
            {% else %}
                <p>You have no active reservations.</p>
            {% endif %}
        </div>
    </div>

    <div class="card checkouts p-3 mb-4 rounded-3">
        <div class="card-body">
            <h2 class="border-bottom mb-4">Checkouts</h2>
            {% if checkouts %}
                <ul>
                    {% for checkout in checkouts %}
                        <li>
                            <strong>Book:</strong> {{ checkout.book.title }}<br>
                            <strong>Checkout Date:</strong> {{ checkout.checkout_date }}<br>
                            <strong>Expected Return Date:</strong> {{ checkout.expected_return_date }}<br>
                            <strong>Return Date:</strong> {{ checkout.return_date|default:"Not Returned" }}
                        </li>
                    {% endfor %}
                </ul>
            {% else %}
                <p>You have no active checkouts.</p>
            {% endif %}
        </div>
    </div>
{% endblock %}

library/templates/library/index.html
{% extends 'library/base.html' %}
{% load static %}
{% block extra_css %}
    <link rel="stylesheet" href="{% static 'library/css/index.css' %}">
{% endblock %}
{% block title %}Home{% endblock %}
{% block content %}
    <section id="sec1">
        <div class="headline"><h1><span class="col-blue">Library<br> </span> a space for <span>accessible knowledge.</span></h1></div>
        <div class="sideimg-div"><img class="sideimg" src="{% static 'library/imgs/girl-reading-book.gif' %}" alt="A gif of a girl reading a book."></div>
    </section>
{% endblock %}

library/templates/library/login.html
{% extends 'library/base.html' %}
{% load static %}
{% block extra_css %}
    <link rel="stylesheet" href="{% static 'library/css/auth.css' %}">
{% endblock %}
{% block title %}Login{% endblock %}
{% block content %}
    <div class="auth-form-cont">
        <h1>Login</h1>
        <form method="POST">
            {% csrf_token %}
            {{ form.as_p }}
            <p>Don't have an account? <a href="{% url 'library:register' %}">Register</a><p>
            <button class="auth-form-btn" type="submit">Login</button>
        </form>
    </div>
{% endblock %}

library/templates/library/register.html
{% extends 'library/base.html' %}
{% load static %}
{% block extra_css %}
    <link rel="stylesheet" href="{% static 'library/css/auth.css' %}">
{% endblock %}
{% block title %}Register{% endblock %}
{% block content %}
    <div class="auth-form-cont">
    <h1>Register</h1>
        <form method="POST">
            {% csrf_token %}
            {{ form.as_p }}
            <p>Already have an account? <a href="{% url 'library:login' %}">Login</a><p>
            <button class="auth-form-btn" type="submit">Register</button>
        </form>
    </div>
{% endblock %}

library/templates/library/top_ten_books.html
{% extends 'library/base.html' %}
{% load static %}
{% block extra_css %}
    <link rel="stylesheet" href="{% static 'library/css/books.css' %}">
{% endblock %}
{% block title %}Book Listing{% endblock %}
{% block content %}
<h1><span class="col-blue">Top Ten</span> Most Popular Books</h1>
<div class="books-cont">
    <div class="books-list">
        {% for book in books %}
            <div class="books-list-item">
                <a href="{% url "library:book_details" book.pk %}">
                    <img src="{{ book.image }}" alt="{{ book.title }} image">
                </a>
                <div class="books-list-item-body">
                    <p>{{ book.title }}</p>
                    <p><span class="param-title">authors:</span>
                        {% for author in book.authors.all %}
                            {{ author.full_name }}{% if not forloop.last %},{% endif %}
                        {% endfor %}
                    </p>
                </div>
            </div>
        {% endfor %}
    </div>
</div>
{% endblock %}